### ISSUE TITLE
GetArray() panic on empty array v1.1.7

### ISSUE THREAD

**Issue by reivaj05** [bottlenose-inc/rapidjson#1]
package main

	import (
		"fmt"

		rj "github.com/bottlenose-inc/rapidjson"
	)

	func main() {

		doc, _ := rj.NewParsedStringJson(`{"test":[]}`)
		ct := doc.GetContainer()
		arrM, _ := ct.GetMember("test")
		fmt.Println(arrM)
		array, _, _ := arrM.GetArray()
		fmt.Println(array)
	}

Result:

    []
	panic: runtime error: index out of range

	goroutine 1 [running]:
	panic(0x4f8a40, 0xc82000a110)
		/usr/local/go/src/runtime/panic.go:464 +0x3e6
	github.com/bottlenose-inc/rapidjson.(*Container).GetArray(0xc82000a3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/javiersv05/work/src/github.com/bottlenose-inc/rapidjson/rapidjson.go:397 +0x1bd
	main.main()
		/home/javiersv05/work/src/github.com/bottlenose-inc/oh-connector-moreover/main.go:15 +0x192
	exit status 2

**Comment by fernandoatagavelab** [comment]
#2
